katapay_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      dbname: katapay
      schema: public
      port: 5432
      threads: 1